version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "1883:1883"  # MQTT port
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    command: >
      sh -c "
      rabbitmq-plugins enable rabbitmq_management;
      rabbitmq-plugins enable rabbitmq_mqtt;
      rabbitmq-plugins enable rabbitmq_mqtt_management;
      rabbitmq-server"
    depends_on:
      - postgres

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  golang:
    image: golang:latest
    container_name: golang
    volumes:
      - .:/go/src/app
    working_dir: /go/src/app
    command: ["go", "run", "main.go"]
    ports:
      - "${PORT}:${PORT}"  # Map container port 8080 to host port 8080
    depends_on:
      - postgres
      - rabbitmq
      - redis

volumes:
  postgres_data:
