version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "1883:1883"  # MQTT port
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    command: >
      sh -c "
      rabbitmq-plugins enable rabbitmq_management;
      rabbitmq-plugins enable rabbitmq_mqtt;
      rabbitmq-plugins enable rabbitmq_mqtt_management;
      rabbitmq-server"
    depends_on:
      - postgres

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  golang:
    image: golang:latest
    container_name: golang
    volumes:
      - .:/go/src/app
    working_dir: /go/src/app
    command: ["go", "run", "main.go"]
    environment:
      DB_HOST: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: 1Nfomedi@2022
      DB_NAME: libar_dev_v3
      HOST: localhost:8100
      DB_SYNC: 0
      DB_PORT: 5432
      RABBIT_URI: amqp://admin:rahmaridho@rabbitmq:5672/
      PORT: 8100
      TEST_PORT: onx_dev
      TELEGRAM_QUEUE_NAME: telegram
      LIVECHAT_QUEUE_NAME: incoming-bot-livechat
      QUEUE_LIVECHAT_INITIATE: onx:onx_quitline:incoming-bot-livechat:onx_quitline_1
      QUEUE_LIVECHAT_BOT: onx:onx_quitline:incoming-bot-livechat:onx_quitline_1:bot
      QUEUE_LIVECHAT_OUTGOING: onx:onx_quitline:incoming-bot-livechat:onx_quitline_1:outgoing
      QUEUE_LIVECHAT_FINISH: onx:onx_quitline:incoming-bot-livechat:onx_quitline_1:finish
      QUEUE_LIVECHAT_HANDOVER: onx:onx_quitline:incoming-bot-livechat:onx_quitline_1:handover
      QUEUE_LIVECHAT_FORWARD: onx:onx_quitline:incoming-bot-livechat:onx_quitline_1:forward
      QUEUE_LIVECHAT_END: onx:onx_quitline:incoming-bot-livechat:onx_quitline_1:end
    ports:
      - "${PORT}:${PORT}"  # Map container port 8080 to host port 8080
    depends_on:
      - postgres
      - rabbitmq
      - redis

volumes:
  postgres_data:
