// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/facebook/{botplatform}/{omnichannel}/{tenantId}/{account}": {
            "post": {
                "description": "Incoming message for channel facebook",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "facebook"
                ],
                "summary": "Incoming facebook",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bot Platform",
                        "name": "botplatform",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Omni Channel",
                        "name": "omnichannel",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tenant",
                        "name": "tenantId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Account",
                        "name": "account",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/webhookFacebook.IncomingDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.Responses"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.Responses"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/facebook/{botplatform}/{omnichannel}/{tenantId}/{account}/end": {
            "post": {
                "description": "End message for channel facebook",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "facebook"
                ],
                "summary": "End facebook",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bot Platform",
                        "name": "botplatform",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Omni Channel",
                        "name": "omnichannel",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tenant",
                        "name": "tenantId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Account",
                        "name": "account",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/webhookFacebook.EndDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.Responses"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.Responses"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/facebook/{botplatform}/{omnichannel}/{tenantId}/{account}/handover": {
            "post": {
                "description": "Handover message for channel facebook",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "facebook"
                ],
                "summary": "Handover facebook",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bot Platform",
                        "name": "botplatform",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Omni Channel",
                        "name": "omnichannel",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tenant",
                        "name": "tenantId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Account",
                        "name": "account",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/webhook.HandoverDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.Responses"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.Responses"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/octopushchat/livechat/{botplatform}/{omnichannel}/{tenantId}/{account}": {
            "post": {
                "description": "Incoming message for channel livechat",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "livechat"
                ],
                "summary": "Incoming livechat",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bot Platform",
                        "name": "botplatform",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Omni Channel",
                        "name": "omnichannel",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tenant",
                        "name": "tenantId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Account",
                        "name": "account",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/webhookLivechat.IncomingDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.Responses"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.Responses"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/octopushchat/livechat/{botplatform}/{omnichannel}/{tenantId}/{account}/end": {
            "post": {
                "description": "End message for channel livechat",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "livechat"
                ],
                "summary": "End livechat",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bot Platform",
                        "name": "botplatform",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Omni Channel",
                        "name": "omnichannel",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tenant",
                        "name": "tenantId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Account",
                        "name": "account",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/webhookLivechat.EndDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.Responses"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.Responses"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/octopushchat/livechat/{botplatform}/{omnichannel}/{tenantId}/{account}/handover": {
            "post": {
                "description": "Handover message for channel livechat",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "livechat"
                ],
                "summary": "Handover livechat",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bot Platform",
                        "name": "botplatform",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Omni Channel",
                        "name": "omnichannel",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tenant",
                        "name": "tenantId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Account",
                        "name": "account",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/webhook.HandoverDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.Responses"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.Responses"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/socioconnect/whatsapp/{botplatform}/{omnichannel}/{tenantId}/{account}": {
            "post": {
                "description": "Incoming message for channel WhatsApp",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "whatsapp"
                ],
                "summary": "Incoming WhatsApp",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bot Platform",
                        "name": "botplatform",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Omni Channel",
                        "name": "omnichannel",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tenant",
                        "name": "tenantId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Account",
                        "name": "account",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/webhookWhatsapp.IncomingDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.Responses"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.Responses"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/socioconnect/whatsapp/{botplatform}/{omnichannel}/{tenantId}/{account}/commerce": {
            "post": {
                "description": "Commerce message for channel WhatsApp",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "whatsapp"
                ],
                "summary": "Commerce WhatsApp",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bot Platform",
                        "name": "botplatform",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Omni Channel",
                        "name": "omnichannel",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tenant",
                        "name": "tenantId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Account",
                        "name": "account",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/webhookWhatsapp.IncomingDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.Responses"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.Responses"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/socioconnect/whatsapp/{botplatform}/{omnichannel}/{tenantId}/{account}/end": {
            "post": {
                "description": "End message for channel WhatsApp",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "whatsapp"
                ],
                "summary": "End WhatsApp",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bot Platform",
                        "name": "botplatform",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Omni Channel",
                        "name": "omnichannel",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tenant",
                        "name": "tenantId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Account",
                        "name": "account",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/webhookWhatsapp.EndDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.Responses"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.Responses"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/socioconnect/whatsapp/{botplatform}/{omnichannel}/{tenantId}/{account}/handover": {
            "post": {
                "description": "Handover message for channel WhatsApp",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "whatsapp"
                ],
                "summary": "Handover WhatsApp",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bot Platform",
                        "name": "botplatform",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Omni Channel",
                        "name": "omnichannel",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tenant",
                        "name": "tenantId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Account",
                        "name": "account",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/webhook.HandoverDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.Responses"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.Responses"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/socioconnect/whatsapp/{botplatform}/{omnichannel}/{tenantId}/{account}/midtrans": {
            "post": {
                "description": "Midtrans message for channel WhatsApp",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "whatsapp"
                ],
                "summary": "Midtrans WhatsApp",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bot Platform",
                        "name": "botplatform",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Omni Channel",
                        "name": "omnichannel",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tenant",
                        "name": "tenantId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Account",
                        "name": "account",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.Responses"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.Responses"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/telegram/{botplatform}/{omnichannel}/{tenantId}/{account}": {
            "post": {
                "description": "Incoming message for channel telegram",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "telegram"
                ],
                "summary": "Incoming telegram",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bot Platform",
                        "name": "botplatform",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Omni Channel",
                        "name": "omnichannel",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tenant",
                        "name": "tenantId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Account",
                        "name": "account",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.Responses"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.Responses"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/telegram/{botplatform}/{omnichannel}/{tenantId}/{account}/end": {
            "post": {
                "description": "End message for channel telegram",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "telegram"
                ],
                "summary": "End telegram",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bot Platform",
                        "name": "botplatform",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Omni Channel",
                        "name": "omnichannel",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tenant",
                        "name": "tenantId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Account",
                        "name": "account",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/webhookTelegram.EndDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.Responses"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.Responses"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/telegram/{botplatform}/{omnichannel}/{tenantId}/{account}/handover": {
            "post": {
                "description": "Handover message for channel telegram",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "telegram"
                ],
                "summary": "Handover telegram",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bot Platform",
                        "name": "botplatform",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Omni Channel",
                        "name": "omnichannel",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tenant",
                        "name": "tenantId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Account",
                        "name": "account",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/webhook.HandoverDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.Responses"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.Responses"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/tole/{queueName}": {
            "post": {
                "description": "Send a message to rabbit tole queue using tenant channel",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tole"
                ],
                "summary": "Send a message to tole queue",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Queue Name",
                        "name": "queueName",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.Responses"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.Responses"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "util.Responses": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                },
                "method": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "webhook.AttributeDTO": {
            "type": "object",
            "required": [
                "accountId",
                "botplatform",
                "channel_id",
                "channel_platform",
                "channel_sources",
                "cust_name",
                "date_timestamp",
                "middleware_endpoint",
                "omnichannel",
                "tenantId",
                "unique_id"
            ],
            "properties": {
                "accountId": {
                    "type": "string"
                },
                "bot_account": {
                    "type": "string"
                },
                "bot_endpoint": {
                    "type": "string"
                },
                "botplatform": {
                    "enum": [
                        "botpress"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/webhook.BotPlatform"
                        }
                    ]
                },
                "channel_id": {
                    "enum": [
                        12,
                        3,
                        7,
                        5
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/webhook.ChannelID"
                        }
                    ]
                },
                "channel_platform": {
                    "enum": [
                        "socioconnect",
                        "maytapi",
                        "octopushchat",
                        "official"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/webhook.ChannelPlatform"
                        }
                    ]
                },
                "channel_sources": {
                    "enum": [
                        "whatsapp",
                        "fbmessenger",
                        "livechat",
                        "telegram"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/webhook.ChannelSources"
                        }
                    ]
                },
                "cust_message": {},
                "cust_name": {
                    "type": "string"
                },
                "date_timestamp": {
                    "type": "string"
                },
                "middleware_endpoint": {
                    "type": "string"
                },
                "new_session": {
                    "type": "boolean"
                },
                "omnichannel": {
                    "enum": [
                        "onx",
                        "on5",
                        "on4"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/webhook.Omnichannel"
                        }
                    ]
                },
                "sid": {
                    "type": "string"
                },
                "stream_id": {
                    "type": "string"
                },
                "tenantId": {
                    "type": "string"
                },
                "unique_id": {
                    "type": "string"
                }
            }
        },
        "webhook.BotPlatform": {
            "type": "string",
            "enum": [
                "botpress"
            ],
            "x-enum-varnames": [
                "BOTPRESS"
            ]
        },
        "webhook.ChannelID": {
            "type": "integer",
            "enum": [
                12,
                3,
                7,
                5
            ],
            "x-enum-varnames": [
                "WHATSAPP_ID",
                "LIVECHAT_ID",
                "FBMESSENGER_ID",
                "TELEGRAM_ID"
            ]
        },
        "webhook.ChannelPlatform": {
            "type": "string",
            "enum": [
                "socioconnect",
                "maytapi",
                "octopushchat",
                "official"
            ],
            "x-enum-varnames": [
                "SOCIOCONNECT",
                "MAYTAPI",
                "OCTOPUSHCHAT",
                "OFFICIAL"
            ]
        },
        "webhook.ChannelSources": {
            "type": "string",
            "enum": [
                "whatsapp",
                "fbmessenger",
                "livechat",
                "telegram"
            ],
            "x-enum-varnames": [
                "WHATSAPP",
                "FBMESSENGER",
                "LIVECHAT",
                "TELEGRAM"
            ]
        },
        "webhook.HandoverDTO": {
            "type": "object",
            "required": [
                "account_id",
                "message",
                "sid",
                "unique_id"
            ],
            "properties": {
                "account_id": {
                    "type": "string"
                },
                "cust_message": {},
                "message": {
                    "type": "string"
                },
                "sid": {
                    "type": "string"
                },
                "unique_id": {
                    "type": "string"
                }
            }
        },
        "webhook.MessageType": {
            "type": "string",
            "enum": [
                "text",
                "image",
                "contacts",
                "document",
                "interactive",
                "button",
                "location",
                "video",
                "sticker",
                "order",
                "unknown",
                "voice",
                "ephemeral"
            ],
            "x-enum-varnames": [
                "TEXT",
                "IMAGE",
                "CONTACTS",
                "DOCUMENT",
                "INTERACTIVE",
                "BUTTON",
                "LOCATION",
                "VIDEO",
                "STICKER",
                "ORDER",
                "UNKNOWN",
                "VOICE",
                "EPHEMERAL"
            ]
        },
        "webhook.Omnichannel": {
            "type": "string",
            "enum": [
                "onx",
                "on5",
                "on4"
            ],
            "x-enum-varnames": [
                "ONX",
                "ON5",
                "ON4"
            ]
        },
        "webhookFacebook.AttachmentPayload": {
            "type": "object",
            "required": [
                "url"
            ],
            "properties": {
                "url": {
                    "type": "string"
                }
            }
        },
        "webhookFacebook.Attachments": {
            "type": "object",
            "required": [
                "payload",
                "type"
            ],
            "properties": {
                "payload": {
                    "$ref": "#/definitions/webhookFacebook.AttachmentPayload"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "webhookFacebook.Data": {
            "type": "object",
            "required": [
                "entry",
                "object"
            ],
            "properties": {
                "entry": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/webhookFacebook.Entry"
                    }
                },
                "object": {
                    "type": "string"
                }
            }
        },
        "webhookFacebook.EndDTO": {
            "type": "object",
            "required": [
                "account_id",
                "message",
                "sid",
                "unique_id"
            ],
            "properties": {
                "account_id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "sid": {
                    "type": "string"
                },
                "unique_id": {
                    "type": "string"
                }
            }
        },
        "webhookFacebook.Entry": {
            "type": "object",
            "required": [
                "id",
                "messaging",
                "time"
            ],
            "properties": {
                "hop_context": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/webhookFacebook.HopContext"
                    }
                },
                "id": {
                    "type": "string"
                },
                "messaging": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/webhookFacebook.Messaging"
                    }
                },
                "time": {
                    "type": "integer"
                }
            }
        },
        "webhookFacebook.HopContext": {
            "type": "object",
            "required": [
                "app_id"
            ],
            "properties": {
                "app_id": {
                    "type": "integer"
                },
                "metadata": {
                    "type": "string"
                }
            }
        },
        "webhookFacebook.IncomingDTO": {
            "type": "object",
            "required": [
                "account",
                "account_name",
                "additional",
                "channel",
                "data",
                "tenant"
            ],
            "properties": {
                "account": {
                    "type": "string"
                },
                "account_name": {
                    "type": "string"
                },
                "additional": {
                    "$ref": "#/definitions/webhook.AttributeDTO"
                },
                "channel": {
                    "type": "string"
                },
                "data": {
                    "$ref": "#/definitions/webhookFacebook.Data"
                },
                "tenant": {
                    "type": "string"
                }
            }
        },
        "webhookFacebook.Message": {
            "type": "object",
            "required": [
                "mid"
            ],
            "properties": {
                "attachments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/webhookFacebook.Attachments"
                    }
                },
                "mid": {
                    "type": "string"
                },
                "quick_reply": {
                    "$ref": "#/definitions/webhookFacebook.QuickReply"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "webhookFacebook.MessagePostback": {
            "type": "object",
            "required": [
                "payload",
                "title"
            ],
            "properties": {
                "payload": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "webhookFacebook.Messaging": {
            "type": "object",
            "required": [
                "recipient",
                "sender",
                "timestamp"
            ],
            "properties": {
                "message": {
                    "$ref": "#/definitions/webhookFacebook.Message"
                },
                "postback": {
                    "$ref": "#/definitions/webhookFacebook.MessagePostback"
                },
                "recipient": {
                    "$ref": "#/definitions/webhookFacebook.Recipient"
                },
                "sender": {
                    "$ref": "#/definitions/webhookFacebook.Sender"
                },
                "timestamp": {
                    "type": "integer"
                }
            }
        },
        "webhookFacebook.QuickReply": {
            "type": "object",
            "required": [
                "payload"
            ],
            "properties": {
                "payload": {
                    "type": "string"
                }
            }
        },
        "webhookFacebook.Recipient": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "webhookFacebook.Sender": {
            "type": "object",
            "required": [
                "first_name",
                "id",
                "last_name",
                "profile_pic"
            ],
            "properties": {
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "profile_pic": {
                    "type": "string"
                }
            }
        },
        "webhookLivechat.EndDTO": {
            "type": "object",
            "required": [
                "account_id",
                "unique_id"
            ],
            "properties": {
                "account_id": {
                    "type": "string"
                },
                "unique_id": {
                    "type": "string"
                }
            }
        },
        "webhookLivechat.IncomingDTO": {
            "type": "object",
            "required": [
                "account",
                "action",
                "dateSend",
                "tenant",
                "user"
            ],
            "properties": {
                "account": {
                    "type": "string"
                },
                "action": {
                    "type": "string"
                },
                "additional": {
                    "$ref": "#/definitions/webhook.AttributeDTO"
                },
                "dateSend": {
                    "type": "string"
                },
                "media": {
                    "$ref": "#/definitions/webhookLivechat.Media"
                },
                "message": {},
                "tenant": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/webhookLivechat.User"
                }
            }
        },
        "webhookLivechat.Media": {
            "type": "object",
            "required": [
                "fileName",
                "fileSize",
                "mimeType",
                "url"
            ],
            "properties": {
                "fileName": {
                    "type": "string"
                },
                "fileSize": {
                    "type": "integer"
                },
                "mimeType": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "webhookLivechat.User": {
            "type": "object",
            "required": [
                "g-recaptcha-response",
                "token"
            ],
            "properties": {
                "g-recaptcha-response": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "webhookTelegram.EndDTO": {
            "type": "object",
            "required": [
                "account_id",
                "message",
                "sid",
                "unique_id"
            ],
            "properties": {
                "account_id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "sid": {
                    "type": "string"
                },
                "unique_id": {
                    "type": "string"
                }
            }
        },
        "webhookWhatsapp.Contacts": {
            "type": "object",
            "required": [
                "wa_id"
            ],
            "properties": {
                "profile": {
                    "$ref": "#/definitions/webhookWhatsapp.Profile"
                },
                "wa_id": {
                    "type": "string"
                }
            }
        },
        "webhookWhatsapp.EndDTO": {
            "type": "object",
            "required": [
                "account_id",
                "message",
                "sid",
                "unique_id"
            ],
            "properties": {
                "account_id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "sid": {
                    "type": "string"
                },
                "unique_id": {
                    "type": "string"
                }
            }
        },
        "webhookWhatsapp.IncomingDTO": {
            "type": "object",
            "required": [
                "account_id",
                "tenant_id",
                "tunnel_url"
            ],
            "properties": {
                "account_id": {
                    "type": "string"
                },
                "additional": {
                    "$ref": "#/definitions/webhook.AttributeDTO"
                },
                "contacts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/webhookWhatsapp.Contacts"
                    }
                },
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/webhookWhatsapp.Messages"
                    }
                },
                "tenant_id": {
                    "type": "string"
                },
                "tunnel_url": {
                    "type": "string"
                }
            }
        },
        "webhookWhatsapp.Messages": {
            "type": "object",
            "required": [
                "timestamp",
                "type"
            ],
            "properties": {
                "timestamp": {
                    "type": "integer"
                },
                "type": {
                    "enum": [
                        "text image contacts document interactive button location video sticker order unknown voice ephemeral"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/webhook.MessageType"
                        }
                    ]
                }
            }
        },
        "webhookWhatsapp.Profile": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Bot Middleware API",
	Description:      "API documentation for the Bot Middleware service.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
